### ISSUE TITLE
Homepage upgrade

### ISSUE THREAD

**Issue by keunes** [AntennaPod/antennapod.github.io#110]
**Short description**:
Spice up the most prominent page with the following elements
- [ ] #104 Integrate more screenshots in landing page
- [ ] #101 Code contributions graph
- [ ] #100 'Latest forum posts' list
- [ ] #97 Display list of features on homepage

**Location**: 
Homepage

**Why have this**: 
See respective issues

**More info**: 
[Mock-up on Penpot](https://design.penpot.app/#/view/d1c45d80-3b12-11ec-a516-23056af0be2f?page-id=d1c45d81-3b12-11ec-a516-23056af0be2f&index=0&share-id=84111db0-3b41-11ec-a516-23056af0be2f)

I didn't implement it in the mock-up, but I think we should only display two rows of features by default, and have a 'Show all' button to unhide the other rows.

@ByteHamster What do you think? I indeed opted not to include some of the elements on the homepage I was thinking of first (contributors list, latest version).

**Comment by ByteHamster** [comment]
Your mock-up looks pretty nice. Still, I'm not sure if I would add the GitHub section (not really relevant to average users and adds more connections to external servers). Also, new users are probably more interested in the features, not in the forum posts. So I would maybe move the blog+forum section down where GitHub is currently displayed.

**Comment by keunes** [comment]
I'm targeting not just the 'average user', but also potential community members, people that believe in FOSS and think AntennaPod is a cool project. That's why I added the forum & GitHub sections: it shows we're active and that you can contribute.

But I agree that the features should be prominent. And they should start above the fold. I created a new version with a smaller block for blog & forum. And another version where this block is moved down, key characteristics is moved up.
https://design.penpot.app/#/view/d1c45d80-3b12-11ec-a516-23056af0be2f?page-id=59a55a90-3c28-11ec-a6dd-9d5f098ad501&index=0&share-id=dbb39570-3c81-11ec-a516-23056af0be2f

You can change between the versions via the selector in the top-left:
![image](https://user-images.githubusercontent.com/11229646/140031145-9e0b633d-86be-4e81-964a-7f60ec257d48.png)

**Comment by keunes** [comment]
> So I would maybe move the blog+forum section down where GitHub is currently displayed

This I didn't try yet. I think we'll then have one big area at the bottom with too many small blocks if I keep the current design. Will try some things later on.

**Comment by ByteHamster** [comment]
Some thoughts:

- The "short" version feels a bit too short to me
- I do have to admit that I visually like the original version (blog posts on top) more than the new design. It somehow feels less "busy" at the bottom.
