### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Rotzbua** [AntennaPod/antennapod.github.io#235]
**Short description**: 

Update dependencies.

**Location**: 

Template.

**Why have this**: 

Keep up with the development.

**Tasks**: 

- [x] Upgrade to latest bootstrap v4 #230
- [x] Upgrade jQuery #230
- [x] Upgrade font fontawesome #234
- [x] Upgrade font Sarabun  #266
- [x] Update github actions #222

**Comment by Rotzbua** [comment]
PR to every task created. So closed.
